Added note about how this is not to be used stand-alone
laminas/laminas-skeleton-installer pull request #10
Opened 2020-07-04 23:00 UTC by TomHAnderson

Signed-off-by: Tom H Anderson <tom.h.anderson@gmail.com>

|    Q          |   A
|-------------- | ------
| Documentation | yes
| Bugfix        | no
| BC Break      | no
| New Feature   | no
| RFC           | no
| QA            | no

### Description

The README.md for this repository said it was a composer plugin but didn't specify that it is not the repository you will want to use to install laminas-mvc-skeleton.  I felt this could be confusing upon searching Laminas github for 'skeleton' projects could not be certain that this wasn't the repository intended to be used to install laminas-mvc-skeleton.

This ambiguity has been alleviated with an additional paragraph.

2020-07-05 04:30 UTC, samsonasik commented on README.md
> +repository and is not inteneded to be used on its own.
typo : /s/inteneded/intended

2020-07-05 05:41 UTC, TomHAnderson commented on README.md
> +repository and is not inteneded to be used on its own.
Fixed.  Thank you.

2020-07-07 15:49 UTC, weierophinney requested changes

2020-07-07 15:49 UTC, weierophinney commented on README.md
> +
```suggestion
**Please note:** this repository is a **composer plugin** for use in skeleton
applications (such as [laminas-mvc-skeleton](https://github.com/laminas/laminas-mvc-skeleton)), 
and is not intended to be installed as a general-purpose package.

```

Its use is not limited to laminas-mvc-skeleton. We actually briefly used it in the Expressive and Apigility skeletons (though the needs of the former required a different approach eventually, and the latter, being highly specialized, has already answered the various "questions" the MVC skeleton asks). As such, I'm making the above suggestion to make that more clear, as well as highlighting that this is a composer plugin, and not a general-purpose package.

2020-09-11 16:59 UTC, merged